### PR TITLE
Fix invalid_origin in clustered environment

### PR DESCRIPTION
**Pull request by wprl**
This applies the basic idea from @iantocristian fix for the clustering issue in the rabbitmq transport.  https://github.com/rjrodger/seneca-rabbitmq-transport/pull/3

This PR sets up a response queue per client so that responses go back to the correct origin.

Although the bug was not fatal as in the rabbitmq transport, it is a potential performance issue.

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
Hey @wprl Is this still valid? If so could you take a look at the merge? If you can't let me know :D

**Comment by wprl** [comment]
I think it is still valid.  About half way through the merge.  Will try to finish by the end of the week.  Cheers

**Comment by mcdonnelldean** [comment]
@wprl Perfect! Thats awesome :D Let me know if I can help in any way.

**Comment by wprl** [comment]
OK merge errors should be resolved.  I wasn't getting tests to pass on the current rjrodger/seneca-beanstalk-transport so I'm not absolutely sure about these changes since I wasn't able to compare tests results between the two repos.

**Comment by mcdonnelldean** [comment]
Closed as out of date.

**Pull request closed without merging**
